### ISSUE TITLE
Extension: Please add simplified time format for Time component converters

### ISSUE THREAD

**Issue by apavelm** [nodatime/nodatime.serialization#109]
It is often needed to specify time or date-time using only "HH:mm" as a time component. Many controls allow specifying only hours and minutes. Seconds are excessive for most of the cases.

It would be nice if you could extend the list of acceptable time formats for "HH:mm" for LocalTime and/or "<date> T HH:MM" for LocalDateTime

of course, the string could always be concatenated with ":00" as seconds, but this look as a "hack" in many scenarios.

Thanks

**Comment by jskeet** [comment]
(I'm assuming this is about one of the JSON converters - in future, please be more specific.)

With the most recent release, you can customize the converters used yourself, using the `NodaJsonSettings` class (there's one in each of NodaTime.Serialization.JsonNet and NodaTime.Serialization.SystemTextJson). Create a new instance, set the appropriate properties (e.g. LocalTimeConverter) - probably using NodaPatternConverter, which again is in both packages - and then pass that into the relevant `ConfigureForNodaTime` method.

**Comment by apavelm** [comment]
@jskeet Sure thing, that was about converters.
And many thanks for the hint!

It is a real killer-feature, but unfortunately not fully described in documentation. I found only 1 line in the documentation *user guide) without any details.
`Custom converters can be created easily from patterns using NodaPatternConverter`

And absolutely nothing there about **CompositePatternBuilder**. Or maybe it structured not optimal way. 

Anyway, thanks a lot for helping!

**Comment by jskeet** [comment]
Yes, I haven't updated the docs yet. I'm afraid documentation often ends up being one thing that gets lost most easily when open source maintainers don't have enough time :( I'll *try* to get to it at some point...
