### ISSUE TITLE
NodaTime Structs as dictionary keys in System.Text.Json

### ISSUE THREAD

**Issue by buvinghausen** [nodatime/nodatime.serialization#114]
Jon I have gone digging it looks like they exposed two virtual functions on [JsonConverter](/dotnet/runtime/blob/main/src/libraries/System.Text.Json/ref/System.Text.Json.cs#L924) in [ReadAsPropertyName](/dotnet/runtime/blob/main/src/libraries/System.Text.Json/ref/System.Text.Json.cs#L931) and [WriteAsPropertyName](/dotnet/runtime/blob/main/src/libraries/System.Text.Json/ref/System.Text.Json.cs#L938) and it doesn't look like the STJ serialization package supports either.

I'm going to take a stab at supporting it and tests and will open a PR as we use LocalDate as a dictionary key and need the support

![image](https://github.com/nodatime/nodatime.serialization/assets/1130210/32cec58f-03f1-46fc-b10c-387395621029)

**Comment by jskeet** [comment]
Righto, sounds good.

**Comment by buvinghausen** [comment]
> Righto, sounds good.

PR up no rush on release as I have just ported the code into our repository and I'm #back2good

**Comment by jskeet** [comment]
Thanks - will get to it when I can. I'm reasonably comfortable ditching the netcoreapp3.1 target now that it's been out of support for a while.

**Comment by buvinghausen** [comment]
Yeah everything below .NET 6 has been out of support for over a year plus if someone is still running on 3.1 or 5 they can still use the .netstandard + STJ nuget shim.

**Comment by jskeet** [comment]
This is fixed in #120, but not yet released. I'll try to get round to a release next weekend, but I'll want to check for anything else we might want to do first.

**Comment by jskeet** [comment]
This is now in version 1.2.0. Please shout if you run into any problems.

**Comment by buvinghausen** [comment]
Thanks Jon!
