### ISSUE TITLE
Look into reports of json.net deserialisation failure for dictionaries keyed by Instant

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime.serialization#2]
Was in https://github.com/nodatime/nodatime/issues/237

See 
http://stackoverflow.com/questions/13941349 and http://stackoverflow.com/q/6845364/634824

**Comment by stevenguh** [comment]
Any update on this?

**Comment by jskeet** [comment]
Just tried it with Json.NET 10.0.3, and it still fails.

To save time in future, here's a complete program:

```csharp
using System;
using System.Collections.Generic;
using NodaTime;
using NodaTime.Serialization.JsonNet;
using Newtonsoft.Json;

class Program
{
    static void Main(string[] args)
    {
        JsonConverter[] converters = { NodaConverters.IntervalConverter, NodaConverters.InstantConverter };

        var dictionary = new Dictionary<Instant, int> {
            { Instant.FromUtc(2012, 1, 2, 3, 4, 5), 0 }
        };
        
        var json = JsonConvert.SerializeObject(dictionary, Formatting.None, converters);
        Console.WriteLine(json);
        var result = JsonConvert.DeserializeObject<Dictionary<Instant, int>>(json, converters);
    }
}
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="NodaTime" Version="2.2.0" />
    <PackageReference Include="NodaTime.Serialization.JsonNet" Version="2.0.0" />
  </ItemGroup>
</Project>
```

Exception:

> Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Could not convert string '2012-01-02T03:04:05Z' to dictionary key type 'NodaTime.Instant'. Create a TypeConverter to convert from the string to the key type object. Path '2012-01-02T03:04:05Z', line 1, position 24

**Comment by stevenguh** [comment]
I have a work around modified from http://stackoverflow.com/q/6845364/634824.
This is by no means performant, and has not been fully tested.

    public class DictionaryWithNodaTimeKeyConverter : JsonConverter
    {
        private static IDateTimeZoneProvider dtzProvider = DateTimeZoneProviders.Tzdb;
        private JsonSerializerSettings _settings;

        public DictionaryWithNodaTimeKeyConverter(IDateTimeZoneProvider dtzProvider)
            : base()
        {
            _settings = new JsonSerializerSettings().ConfigureForNodaTime(dtzProvider);
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            IDictionary dictionary = (IDictionary)value;
            writer.WriteStartObject();

            foreach (object key in dictionary.Keys)
            {
                writer.WritePropertyName(ConvertToPropertyKey(key));
                serializer.Serialize(writer, dictionary[key]);
            }

            writer.WriteEndObject();
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null)
            {
                return null;
            }

            Type keyType = objectType.GetGenericArguments()[0];
            Type valueType = objectType.GetGenericArguments()[1];

            Type intermediateDictionaryType = typeof(Dictionary<,>).MakeGenericType(typeof(string), valueType);
            IDictionary intermediateDictionary = (IDictionary)Activator.CreateInstance(intermediateDictionaryType);
            serializer.Populate(reader, intermediateDictionary);

            IDictionary finalDictionary = (IDictionary)Activator.CreateInstance(objectType);
            foreach (DictionaryEntry pair in intermediateDictionary)
            {
                object parsedObject;
                if (TryConvertKey(pair.Key.ToString(), keyType, out parsedObject))
                {
                    finalDictionary.Add(parsedObject, pair.Value);
                }
            }

            return finalDictionary;
        }

        public override bool CanConvert(Type objectType)
        {
            bool canConvert = objectType.IsA(typeof(IDictionary<,>));

            if (canConvert)
            {
                Type keyType = objectType.GetGenericArguments()[0];
                canConvert = canConvert && IsNodaTimeType(keyType);
            }

            return canConvert;
        }

        private bool IsNodaTimeType(Type type)
        {
            return type.IsA(typeof(Instant))
                    || type.IsA(typeof(OffsetDateTime))
                    || type.IsA(typeof(DateTimeZone))
                    || type.IsA(typeof(ZonedDateTime))
                    || type.IsA(typeof(LocalDateTime))
                    || type.IsA(typeof(LocalDate))
                    || type.IsA(typeof(LocalTime))
                    || type.IsA(typeof(Offset))
                    || type.IsA(typeof(Duration))
                    || type.IsA(typeof(Period));
            // Interval is not Support because Interval is serialized as a compound object.
        }

        private string ConvertToPropertyKey(object property)
        {
            if (!IsNodaTimeType(property.GetType()))
            {
                throw new InvalidOperationException();
            }

            string result = JsonConvert.SerializeObject(property, _settings);
            if (!string.IsNullOrWhiteSpace(result))
            {
                // Remove the "" from JsonConvert
                int first = result.IndexOf('"');
                int last = result.LastIndexOf('"');
                if (first != -1 && last != -1 && first < last)
                {
                    result = result.Substring(first + 1, last - (first + 1));
                }
            }

            return result;
        }

        private bool TryConvertKey(string text, Type keyType, out object value)
        {
            if (!IsNodaTimeType(keyType))
            {
                throw new InvalidOperationException();
            }

            value = keyType.CreateDefault();

            try
            {
                value = JsonConvert.DeserializeObject($"\"{text}\"", keyType, _settings);
                return true;
            }
            catch
            {
                return false;
            }
        }
    }

I also defined some extensions

    public static class TypeExtensions
    {
        public static bool IsA(this Type type, Type typeToBe)
        {
            if (!typeToBe.IsGenericTypeDefinition)
                return typeToBe.IsAssignableFrom(type);

            List<Type> toCheckTypes = new List<Type> { type };
            if (typeToBe.IsInterface)
                toCheckTypes.AddRange(type.GetInterfaces());

            Type basedOn = type;
            while (basedOn.BaseType != null)
            {
                toCheckTypes.Add(basedOn.BaseType);
                basedOn = basedOn.BaseType;
            }

            return toCheckTypes.Any(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeToBe);
        }

        public static object CreateDefault(this Type type)
        {
            return type.IsValueType ? Activator.CreateInstance(type) : null;
        }
    }

To use it:

    IDateTimeZoneProvider provider = DateTimeZoneProviders.Tzdb;
    JsonConverter[] converters = { NodaConverters.IntervalConverter, NodaConverters.InstantConverter, new DictionaryWithNodaTimeKeyConverter(provider) };

    var dictionary = new Dictionary<Instant, int> {
        { Instant.FromUtc(2012, 1, 2, 3, 4, 5), 0 }
    };

    var json = JsonConvert.SerializeObject(dictionary, Formatting.None, converters);
    Console.WriteLine(json);
    var result = JsonConvert.DeserializeObject<Dictionary<Instant, int>>(json, converters);

**Comment by jskeet** [comment]
Right. While this sort of workaround is good to know about, I don't think it belongs in Noda Time itself. Fundamentally this is a bigger problem that is much better solved within Json.NET. In particular, we wouldn't want to handle *every* kind of collection...

At this point, I'm tempted to close the issue as effectively unfeasible (from a "changes to Noda Time" perspective) - what do you think?

**Comment by stevenguh** [comment]
I posted the issue over Json.NET, and hopefully we can find a better solution than this workaround.

**Comment by stevenguh** [comment]
Base the discussion on the Json.NET repo, it seems like we need to implement TypeConverter either in this repo or the main repo in order to serialize NodaTime as dictionary key. What do you think? I am happy to help if that's needed.

**Comment by jskeet** [comment]
Okay, so that would be in the main repo? I'll do some prototyping and see how deep an impact it would have elsewhere. I'll raise a new issue there, linking to this.

**Comment by stevenguh** [comment]
I actually created some NodaTime type converters similar to NodaConverters in this repo that use `IPattern<T>`. It's fairly straight froward except `DateTimeZone` and `ZonedDateTime`, where their patterns need to take an `IDateTimeZoneProvider `. The problem being a derived class of `TypeConverter` can't take any parameter.

I have to basically do something similar to https://stackoverflow.com/a/14933650/2563765 where the TypeConverter will try to look at another attribute which contains the `IDateTimeZoneProvider`.

Since I don't have the control of the main repo, I have to do something like this which allows me to add attributes on runtime, and with a provider that is not statically defined.

```csharp
TypeDescriptor.AddAttributes(typeof(ZonedDateTime), new DateTimeZoneProviderAttribute(provider));
TypeDescriptor.AddAttributes(typeof(ZonedDateTime), new TypeConverterAttribute(typeof(ZonedDateTimeTypeConverter)));

```

**Comment by jskeet** [comment]
Interesting. If we had the attributes and type converters in the main repo, presumably you'd still be able to use `TypeDescriptor.AddAttributes`? Or does it only work if the first attribute has been added dynamically too?

I like the idea of keeping this out of the main repo if possible - potentially with a third separate serialization package, as I can imagine this *could* be useful for non-JSON scenarios as well. If we provided a similar "setup" method to the one we do for JSON.NET to add the attributes dynamically, do you think that would be simple enough for most use cases, or is there a significant benefit in them working out of the box (i.e. living in NodaTime.dll itself)?

**Comment by stevenguh** [comment]
I have not tried doing `TypeDescriptor.AddAttributes` with a statically defined attribute. My gut sense is that it will replace any defined attribute with the same name. I tried calling the same `TypeDescriptor.AddAttributes` twice, it didn't add new attribute when I inspected with `TypeDescriptor.GetAttributes`.

I also like the idea to keep this out of main repo esp because statically defined TypeConverter wouldn't help in the case of the `ZonedDateTime` and `DateTimeZone`. I actually created something like `ConfigureForNodaTime` that takes in a `IDateTimeZoneProvider` and setup all the type converters in run time.

I think it would be simple enough for the case of Json.NET, I literally just have an extra setup after `ConfigureForNodaTime`

I can't speak for `PropertyGrid` as I have never used it before, but I wouldn't think it would be any different. I imagine it would just be an extra setup of the application.

**Comment by jskeet** [comment]
Righto. I'll look at doing this as a separate small project.
I suspect that configuring type converters at execution time may not work well in VS designer situations, but we'll see...

**Comment by buvinghausen** [comment]
https://github.com/nodatime/nodatime/pull/1237

I think you can close this out with the caveat that you either need to pull the code from 1237 or wait for the 3.0 release which will contain the TypeConverters.

**Comment by jskeet** [comment]
Thanks, closing.
