### ISSUE TITLE
Upgrade to .NET Standard 2.0

### ISSUE THREAD

**Issue by petriashev** [nodatime/nodatime.serialization#22]
- remove net451, remove netcoreapp1.0, add netstandard2.0 instead
- simplify projects
- simplify travis build

**Comment by jskeet** [comment]
I'm not going to remove netstandard1.3 or net451 support within the 2.x range. It would need a major version bump. I'm happy to add a netstandard2.0 target though.

**Comment by jskeet** [comment]
I've updated protobuf to netstandard2.0 and added a netstandard2.0 target for the Json.NET library. Closing this now as I've done everything I think we should.
