### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by petriashev** [nodatime/nodatime.serialization#25]
Please release 2.1.0 because no issues with beta for 4 month.

**Comment by jskeet** [comment]
Right - and there have been enough downloads to know that it's almost certainly not completely broken :)

I'll need to work out what releasing requires in the serialization space - we haven't done nearly as many of these releases as for the regular NodaTime project - but I'll try to get to it in the next week or two. Thanks for the nudge :)

**Comment by petriashev** [comment]
Its time for open source! )

**Comment by jskeet** [comment]
It's the holidays, and I'm busy doing non-computer things. It's on my list when I can get to it.

**Comment by jskeet** [comment]
Now done :)
