### ISSUE TITLE
New library on offer for Serilog destructuring of NodaTime types

### ISSUE THREAD

**Issue by kingboyk** [nodatime/nodatime.serialization#26]
I've written a library which destructures NodaTime objects in order for them to be cleanly logged in Serilog. The destructuring policies were copied from NodaTime.Serialization.JsonNet, and the JSON created by Serilog after destructuring by my library is roundtrip deserializable by NodaTime.Serialization.JsonNet. This is backed by unit tests.  The log entries are also much more compact and human readable than without the library.

I'd like to find the code a home and was wondering if you would review it for inclusion in this repo or elsewhere within the organisation? Strictly speaking it could be said that destructuring is the step _before_ deserialization but it might be close enough?

If you're interested to take a look could you please let me know:

- The desired project location and project and namespace names
- Framework targets (I'm currently targetting .NET Standard 2.0 in the library proper and .NET Core 2.2 in the unit tests)
- Whether I need to fork and then branch, or just fork

...and I'll get a PR put together.

**Comment by jskeet** [comment]
Hmm. Is there any particular reason you'd want it within the Noda Time project itself, rather than as part of your own repo? I'd rather not take on more maintenance burden (even just releasing, hosting the docs etc is non-trivial effort).

**Comment by kingboyk** [comment]
There are 2 main reasons why I thought I would offer it you Jon - discoverability and credibility.  I think people are more likely to find and use it if it hosted by either NodaTime or Serilog. Of the 2, NodaTime seems more appropriate as they're your types :) Also, I wanted to give something back and help the cause (as you helped me personally when Noda Time was new).

However, if you don't want to take on another project that's fine of course, and perfectly understandable. In that case I'd probably publish it myself (but not for some time, until the project I am using it in is ready).

**Comment by jskeet** [comment]
I think publishing it yourself when you're ready to do so is probably the best plan - at least for now. There are plenty of other projects which are add-ons using Noda Time - it's possible that for the sake of discoverability we should have a page in the docs about them all, which could of course include a link to your package.

Closing this issue for now.
