### ISSUE TITLE
Request for NodaTime.OffsetDate converting

### ISSUE THREAD

**Issue by artfulsage** [nodatime/nodatime.serialization#28]
Hi. Please add converter for `NodaTime.OffsetDate` to `ConfigureForNodaTime()` extension methods.

**Comment by jskeet** [comment]
That seems doable - with OffsetTime at the same time. For the moment, it should be easy enough to work around with a suitable `NodaPatternConverter`.

**Comment by artfulsage** [comment]
Sample for those who also needs this for now
```cs
var settings = new JsonSerializerSettings();
settings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
settings.Converters.Add(new NodaPatternConverter<OffsetDate>(OffsetDatePattern.GeneralIso));
```

**Comment by jskeet** [comment]
This is now part of 2.2.0-beta01
