### ISSUE TITLE
JSON deserialization throws NodaTime.Text.UnparsableValueException

### ISSUE THREAD

**Issue by daniel-white** [nodatime/nodatime.serialization#32]
Given

```
class Program
{
    static void Main(string[] args)
    {
        var json = @"{ ""value"": ""2012-12-12"" }";
        JsonSerializerSettings settings = new JsonSerializerSettings();
        settings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
        var model = JsonConvert.DeserializeObject<Model>(json, settings);
    }
}

class Model
{
    public ZonedDateTime Value { get; set; }
}
```

The `DeserializeObject` call throws the NodaTime specific `NodaTime.Text.UnparsableValueException`. In ASP.NET Core MVC, this results in a 500. I would have expected a `JsonSerializationException` that includes the property name. I believe ASP.NET Core MVC looks for that exception to formulate a 400 response instead.

I know this is perhaps a breaking behavior change that could go with either this project or JSON.Net.

Thanks!

**Comment by jskeet** [comment]
I don't believe our code actually sees the property name - this is something I'd expect Json.NET to potentially handle by wrapping our exception in a `JsonSerializationException` with the property name.
There's unfortunately relatively sparse documentation on how `JsonConverter` is expected to be implemented :(

I can look at it at some point, but it's unlikely to be soon I'm afraid.

**Comment by daniel-white** [comment]
Thanks @jskeet. I know its a grey area as to who is responsible for it.

**Comment by daniel-white** [comment]
@jskeet it looks like the `JsonReader` has everything required to construct a `JsonSerializationException`. The positional information is on a derived `JsonTextReader`. 

Would this be something you'd take a PR for?

**Comment by jskeet** [comment]
Yes, very happy to! While changing the exception type is not great in terms of compatibility, I wouldn't expect anyone to be actually catching this...

**Comment by daniel-white** [comment]
Doh. The version that this project references doesn't have that overload. It would require bumping up to a later version of JSON.NET.

**Comment by jskeet** [comment]
Well that's definitely an option - even though normally a major version bump of a dependency *should* be a major version bump of the package that depends on it, I think Json.NET is sufficiently stable that a minor version would be okay.

**Comment by daniel-white** [comment]
Sounds good. I'll find the minimum version of json.net that has the constructor it needs and use that

**Comment by jskeet** [comment]
This is now part of release 2.2.0-beta01

**Comment by daniel-white** [comment]
just tested the beta. the mvc layers are now returning a 400. thanks!
