### ISSUE TITLE
Will deserializing into an Instant fail if the UTC indicator (z) isn't present in the string?

### ISSUE THREAD

**Issue by johnknoop** [nodatime/nodatime.serialization#42]
I'm probably just to lazy to set up and test this myself, so I thought I might ask if you guys know this off the top of your head.

If I try to deserialize this piece of JSON

```json
{
  "myDate": "2019-07-10T21:27:00"
}
```
into this type
```csharp
class MyClass
{
  public Instant MyDate { get; set; }
}
```
...will the JSON.NET extension accept the value or will it complain about the format not indicating that it's in UTC?

Thanks

**Comment by jskeet** [comment]
I don't know off the top of my head, but I *suspect* it would need the Z. That value would work for a LocalDateTime, I expect.

**Comment by johnknoop** [comment]
The reason for asking is that we're looking to add some validation when data is posted from the browser to the backend, and would like it to fail if the date strings aren't in the expected format.

I'll set up a sample project and verify it.

Thanks.
