### ISSUE TITLE
Add case-insensitive deserialization for JSON

### ISSUE THREAD

**Issue by yoPCix** [nodatime/nodatime.serialization#60]
Currently deserialization is always case-sensitive without any option to make it case-insensitive. This is contrary to how the underlying Newtonsoft.Json operates which is case-insensitive by default.
Result is that switching casing on serialization side breaks deserialization side.
Especially when upgrading from an older NodaTime (e.g. 1.4 which was always PascalCase) to latest version (2.4), which now respects `JsonSerializerSettings.ContractResolver` setting.
Example: `Interval` class has `Start` and `End` properties that are case-sensitive when deserializing.

**Comment by jskeet** [comment]
Given that this is an area it sounds like you're more familiar with than I am, would you be able to create a pull request to fix it? I'm unlikely to be able to find time to investigate and fix this - at least any time soon.

**Comment by jskeet** [comment]
This code is now merged, but I'll leave the issue open for now as a reminder that I need to do a release.

**Comment by jskeet** [comment]
I've now released NodaTime.Serialization.JsonNet 2.3.0.

I still need to write up the releases on nodatime.org, but that shouldn't block you.
