### ISSUE TITLE
Posting ZonedDateTime Json return Bad Request 

### ISSUE THREAD

**Issue by MahmoudSamir101** [nodatime/nodatime.serialization#64]
I'm not sure if it is issue or I'm doing something wrong.
I have an API that return json of ZonedDateTime, when I used that json to send it as query string to the Api it always returns bad request.

I tried to send the value of that date by doing zonedDateTime.ToString() as a query string and it worked , you can find that below

The returned Json from the Api :
2020-05-22T04:37:50.6817749+03 Asia/Riyadh

Sending it as a query string after encoding,always returns bad request:
2020-05-22T04:37:50.6817749%2B03%20Asia/Riyadh --> 2020-05-22T04:37:50.6817749+03 Asia/Riyadh

Sending as the return value of ToString() method it worked:
2020-05-22T04:37:50%20Asia/Riyadh%20(%2B03) --> 2020-05-22T04:37:50 Asia/Riyadh (+03)

Packages versions that I used:
Asp.net core version 5.0
NodeTime  version 3.0.0-beta02
NodaTime.Serialization.SystemTextJson version 1.0.0-beta02

    Class Startup {
    public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers().AddJsonOptions(options =>
            {
                
    options.JsonSerializerOptions.ConfigureForNodaTime(NodaTime.DateTimeZoneProviders.Tzdb);
                options.JsonSerializerOptions.WithIsoDateIntervalConverter();
                options.JsonSerializerOptions.WithIsoIntervalConverter();
            });
            services.AddScoped<NodaTime.IClock, NodaTime.SystemClock>(p => 
    NodaTime.SystemClock.Instance);
            
        }
    }

    ApiController{

    public  ZonedDateTime Get(string zoneId, ZonedDateTime date)
        {
            zoneId ??= DateTimeZoneProviders.Tzdb.GetSystemDefault().Id;
            var zone = DateTimeZoneProviders.Tzdb[zoneId];
            var now = new ZonedDateTime(clock.GetCurrentInstant(), zone);
            return now;
        }

    }
`
Appreciate any help & Thanks

**Comment by MahmoudSamir101** [comment]
There is no client code, I'm just trying from swagger-ui by sending a query string variable.
If you want me to make a client code, I can do it

**Comment by jskeet** [comment]
Okay, thanks - I'll look into it when I get a chance, hopefully over the weekend (but possibly not before that; today is busy)

**Comment by malcolmr** [comment]
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/model-binding suggests to me that model binding only uses `System.Text.Json` when parsing data in the request body, not for the query parameters.

That reference doesn't actually say so, but I strongly suspect that query parameters are handled by the type's `TypeConverter`, which in this cases uses `ZonedDateTimePattern.ExtendedFormatOnlyIso`.

`ToString()` ends up using `ZonedDateTimePattern.GeneralFormatOnlyIso` (same as the extended pattern, but no fractional seconds), which is compatible with `ExtendedFormatOnlyIso`, so I suspect that's why that format works.

**Comment by MahmoudSamir101** [comment]
ok is it applicable to force the serializer to generate the same format that works with the query string, as the problem will occur when the api returns a date in a format and the client uses this format to query the api again through url segment or a query string, it is annoying that every time the client wants to query the api by a date field, he needs to convert the serialized  json to another format

**Comment by jskeet** [comment]
I suspect the simplest option here is to change the parameter in your method to be just `string` and then parse explicitly using a suitable `ZonedDateTimePattern` (which would be `ZonedDateTimePattern.ExtendedFormatOnly` but with a suitable `IDateTimeZoneProvider`).

While you *could* replace the formatter used for the JSON, it feels better to me to just be explicit in how you're treating the query string.

**Comment by MahmoudSamir101** [comment]
**@malcolmr** based on your link, I checked the custom binder option, and it is worked, the same value that returned from api as json can be sent as a query string and the parameter type is **ZonedDateTime** not a **string**.

the solution to create a ### ModelBinder for type **ZonedDateTime**, and register it globally as the first model binder

> Create Model Binder Provider

    public class ZonedDateTimeModelBinderProvider : IModelBinderProvider
    {
        public IModelBinder GetBinder(ModelBinderProviderContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            if (context.Metadata.ModelType == typeof(ZonedDateTime))
            {
                return new BinderTypeModelBinder(typeof(ZonedDateTimeBinder));
            }
            return null;
        }
    }

> Create Model Binder

     public class ZonedDateTimeBinder : IModelBinder
    {
        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            if (bindingContext == null)
            {
                throw new ArgumentNullException(nameof(bindingContext));
            }

            var modelName = bindingContext.ModelName;

            var valueProviderResult = bindingContext.ValueProvider.GetValue(modelName);

            if (valueProviderResult == ValueProviderResult.None)
            {
                return Task.CompletedTask;
            }

            bindingContext.ModelState.SetModelValue(modelName, valueProviderResult);

            var value = valueProviderResult.FirstValue;

            if (string.IsNullOrEmpty(value))
            {
                return Task.CompletedTask;
            }
            var zonedDateTime = ZonedDateTimePattern.CreateWithInvariantCulture("uuuu'-'MM'-'dd'T'HH':'mm':'ss;FFFFFFFFFo<G> z",DateTimeZoneProviders.Tzdb).Parse(value);
            
            if (!zonedDateTime.Success)
            {
                bindingContext.ModelState.TryAddModelError(
                    modelName, zonedDateTime.Exception.ToString());
                return Task.CompletedTask;
            }

            bindingContext.Result = ModelBindingResult.Success(zonedDateTime.Value);
            return Task.CompletedTask;
        }
    }

> Register Model Binder Provider

     public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers(options=>
            {
                **options.ModelBinderProviders.Insert(0, new ZonedDateTimeModelBinderProvider());**
            }).AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.ConfigureForNodaTime(NodaTime.DateTimeZoneProviders.Tzdb);
                options.JsonSerializerOptions.WithIsoDateIntervalConverter();
                options.JsonSerializerOptions.WithIsoIntervalConverter();
            });
            services.AddTransient<NodaTime.IClock, NodaTime.SystemClock>(p => NodaTime.SystemClock.Instance);         
        }
    }

**@jskeet** I prefer to not explicitly convert the parameters from **string** to **ZonedDateTime** as the other types such as **Instance**, **LocalDate**, **LocalDateTime** and **OffsetDateTime** are working with query string without any issues, so maybe the solution is a workaround for my case.

**Comment by jskeet** [comment]
Hmm... I would say it's more through *coincidence* than anything else that the other types are working. We happen to use the same format for the type converter as for the JSON representation in the other types. While you're welcome to keep treating ZonedDateTime separately, I'd personally be more explicit about it.

Anyway, I'll close the issue now, as I don't think a change is required in Noda Time either way.
