### ISSUE TITLE
[Question] When are you going to release NodaTime.Serialization.SystemTextJson?

### ISSUE THREAD

**Issue by Ilchert** [nodatime/nodatime.serialization#66]
Nodatime 3.0 has been released recently but NodaTime.Serialization.SystemTextJson still in beta, are you going to publish release version?

**Comment by jskeet** [comment]
Yes, I will do at some point, and it will probably target NodaTime 3.0.
But I have a *lot* of other things on (in terms of both personal and work projects) and I'm reluctant to commit to a date at this point.

**Comment by Ilchert** [comment]
Wow! So fast answer from Jon Skeet :). Thanks for your contribution to .net!

**Comment by jskeet** [comment]
Released now.
