### ISSUE TITLE
Different formats used in TypeConverters and serialization for Durations

### ISSUE THREAD

**Issue by lundmikkel** [nodatime/nodatime.serialization#68]
I love the new type converters in NodaTime 3.0, but the converter for `Duration` is giving me a headache.

There isn't an ISO 8601 format for `Duration` ([the duration mention there](https://en.wikipedia.org/wiki/ISO_8601#Durations) is a `Period`), but I would have preferred that Noda Time at least used a consistent format.

Noda Time's `DurationTypeConverter` uses `DurationPattern.Roundtrip` with the format `-D:hh:mm:ss.FFFFFFFFF`, whereas NodaTime.Serialization's `ConfigureForNodaTime()` uses (a custom format equal to) `DurationPattern.JsonRoundtrip` with the format `-H:mm:ss.FFFFFFFFF` instead.

That means that in order to have a consistent format everywhere, we need to write code like this:
```csharp
serializerSettings
    // Adds default serializers
    .ConfigureForNodaTime(DateTimeZoneProviders.Tzdb)

    // Change Duration format to match TypeConverter
    .Converters.Insert(0, new NodaPatternConverter<Duration>(DurationPattern.Roundtrip));
```

I personally prefer the standard round trip format with days, as it is much easier to understand by a human. But regardless of which format is chosen, I think the two formats should agree.

**Comment by lundmikkel** [comment]
Alternatively, you could use the `CompositePatternBuilder<T>` to accept both formats in the TypeConverter. But I expect that would fail for `ConvertTo` 🤔

**Comment by jskeet** [comment]
This is now slightly easier to do with `NodaJsonSettings`:

```csharp
serializerSettings.ConfigureForNodaTime(new NodaJsonSettings { DurationConverter = new NodaPatternConverter<Duration>(DurationPattern.Roundtrip) })
```

... but adding a `DurationRoundTripConverter` would make it even easier:

```csharp
serializerSettings.ConfigureForNodaTime(new NodaJsonSettings { DurationConverter = NodaConverters.DurationRoundTripConverter })
```

That's probably the solution we'll end up with - so I just need to add `DurationRoundTripConverter` and finally get round to adding some documentation for `NodaJsonSettings`.

**Comment by jskeet** [comment]
This is now merged (but not released) - with a name of RoundtripDurationConverter, to be consistent with the other properties.
