### ISSUE TITLE
New project: NodaTime.Protobuf

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime.serialization#7]
Now that 2.0 is out (well, building) and serialization is in a different repo, we can start another serialization project: integration with Google.Protobuf.

This will provide simple conversions between the Noda Time Instant/Duration types and the Protobuf Timestamp/Duration types, as well as possibly the types in Google.Type (TimeOfDay, Date).

**Comment by jskeet** [comment]
Certainly at some point - I just need to find more time to add appropriate polish etc :)

**Comment by adamwrs** [comment]
I was just playing around with prototyping something, and thought I would see if that was available.  It’ll probably be a few months before I actually really _need_ it.  So I can wait for the polish. Thanks for asking! :)

**Comment by jskeet** [comment]
1.0.0-beta01 now released. Closing this for now, although there's still some more I'd like to do before 1.0.0.
