### ISSUE TITLE
SystemTextJson package updates have not been published to Nuget

### ISSUE THREAD

**Issue by Khitiara** [nodatime/nodatime.serialization#96]
The latest version of NodaTime.Serialization.SystemTextJson is 1.0.0 according to nuget at https://www.nuget.org/packages/NodaTime.Serialization.SystemTextJson and it appears there have been code changes in the package since - any plans to get changes pushed out?

**Comment by jskeet** [comment]
Not imminently, but I'll try to get to this in August. There are a few other changes I'd like to get to first.

**Comment by Khitiara** [comment]
Alright, thanks!

**Comment by jskeet** [comment]
I've pushed 1.1.0 now. It should be available soon.
